### ISSUE TITLE
请问会不会发生离屏渲染

### ISSUE THREAD

**Issue by Q-binbin** [panghaijiao/HJCornerRadius#1]
请问会不会发生离屏渲染

**Comment by panghaijiao** [comment]
确保imageview.layer.masksToBounds = NO  是不会触发离屏渲染问题的

**Comment by iphone-andy** [comment]
这是消耗资源最小的实现方式么

**Comment by panghaijiao** [comment]
不能确定是不是资料消耗最小，但是可以解决界面圆角过多导致离屏渲染的问题

**Comment by longhongwei17** [comment]
感觉 FPS下降了

**Comment by panghaijiao** [comment]
确保 imageview.layer.masksToBounds = NO

**Comment by italianshen** [comment]
我用了之后怎么内存还比 用cornersRadius + maskToBounds内存还高 我之前用cornersRadius + maskToBounds内存是45M左右 用了 _iconView.aliCornerRadius = 15.0;
    _iconView.layer.masksToBounds = NO;之后直接增加到107M

**Comment by panghaijiao** [comment]
是的，这个弊病在于内存消耗较大
