### ISSUE TITLE
朋友你好

### ISSUE THREAD

**Issue by liuzhiyi1992** [panghaijiao/HJCornerRadius#2]
你好

**Comment by panghaijiao** [comment]
您好：

很高兴认识你，关于你的疑问，我跟你说说我这篇文章的来源吧

3月10号，看到iOS开发周报(http://www.infoq.com/cn/news/2016/03/ios-weekly-oculus-rift-mac)里面一篇介绍图片圆角的文章（http://www.jianshu.com/p/f970872fdc22），文章主要介绍了剪接UIImage的想法，恰逢公司项目用到了大量图片圆角，鄙人正在做这方面的优化，因此，就想试一试，这个跟您所说的CoreGraphics以及Category思想是一致的
至于KVO，runtime，不知道您是否看过我的这篇文章 "自释放"在iOS开发中的应用（http://www.olinone.com/?p=232），我在文中详细介绍了动态属性方法，甚至还开源过一个改造的项目https://github.com/panghaijiao/HTBKVObservationCategory，KVO思想来源已久，并被广泛使用

当然，您的疑问也让我开始重视起版权的保护，谢谢你！
本人QQ：275742376   交个朋友吧！您的博客我很喜欢，开源了不少好项目，如果您看得起，能不能做个博客的友情互链？

期待你的回复

**Comment by liuzhiyi1992** [comment]
很高兴收到朋友的回应。其实一开始朋友发链接告诉我的时候我也觉得没什么，后来又看见HJCornerRadius的readme连我那边的四块svg的牌也拿去了我才感觉有问题，而又没有看见注明参考和来源之类的，于是觉得有必要发个issues问下原由。

朋友的博客前天我也刨了半天，有很多值得学习的思想，之前就收藏起来慢慢吸收了。

**Comment by panghaijiao** [comment]
呵呵，相互学习
