### ISSUE TITLE
pod install 失败

### ISSUE THREAD

**Issue by sysatom** [panghaijiao/HJCornerRadius#3]
![f9b6e8686b25](https://cloud.githubusercontent.com/assets/1270641/14268952/82cb3672-fb12-11e5-87d3-88c2d51865ab.png)

**Comment by panghaijiao** [comment]
刚验证了，没问题，请确定输入的是完整git地址，感谢你的来访

target 'Test' do

pod 'HJCornerRadius', :git => "https://github.com/panghaijiao/HJCornerRadius.git"

end

➜  Test git:(master) ✗ pod install
Updating local specs repositories

CocoaPods 1.0.0.beta.6 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Pre-downloading: `HJCornerRadius` from `https://github.com/panghaijiao/HJCornerRadius.git`
Downloading dependencies
Installing HJCornerRadius (0.0.1)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `Test.xcworkspace` for this project from now on.
Sending stats
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total
pod installed.
➜  Test git:(master) ✗

**Comment by mailworks** [comment]
v1.0.0对podspec语法有改变，见 https://github.com/panghaijiao/HJCornerRadius/pull/5

**Comment by panghaijiao** [comment]
好，我更新下最新版看看
