### ISSUE TITLE
内存占用很大

### ISSUE THREAD

**Issue by Liqiankun** [panghaijiao/HJCornerRadius#4]
不用这内存占用是10用了为40

**Comment by panghaijiao** [comment]
这个原则上是会占用更多的cpu，占用内存目前还没有验证过，有时间验证下！不过不推荐所有界面圆角都用这个，优先使用系统圆角，如果界面圆角太多影响滑动时，再考虑该方案。

**Comment by Liqiankun** [comment]
谢回复！^^

**Comment by panghaijiao** [comment]
我刚才验证下，貌似没有发现你这边所说的占用内存从10到40这种情况，能大致介绍一下你这边的测量方法吗？
