### ISSUE TITLE
当我切割圆角以后 为图片设置边框线 边框线还是方形而不是圆形 这是为什么啊

### ISSUE THREAD

**Issue by Gugogogo** [panghaijiao/HJCornerRadius#6]

**Comment by panghaijiao** [comment]
因为这个并没有修改view的layer，操作对象只是view，如果需要边框圆形，可以使用view.layer.corner，但是不要开启view.layer.maskBound，这样就不会出现问题了

**Comment by Gugogogo** [comment]
经你的提醒问题已经解决 谢谢啊

在 2016年6月17日，下午4:49，庞海礁 <notifications@github.com<mailto:notifications@github.com>> 写道：

因为这个并没有修改view的layer，操作对象只是view，如果需要边框圆形，可以使用view.layer.corner，但是不要开启view.layer.maskBound，这样就不会出现问题了
